"""unique to users.username

Revision ID: 2568c1d209f2
Revises: cd811f6bfec1
Create Date: 2025-01-19 13:16:24.211497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2568c1d209f2'
down_revision = 'cd811f6bfec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint("uq_users_username", ['username'])
        batch_op.drop_column('role')
        batch_op.drop_column('u_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('u_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.TEXT(), nullable=True))
        batch_op.drop_constraint("uq_users_username", type_='unique')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
