"""empty message

Revision ID: 42c4eac64852
Revises: 2568c1d209f2
Create Date: 2025-01-19 18:25:31.038072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c4eac64852'
down_revision = '2568c1d209f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_id', sa.Integer(), nullable=False))
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('u_id')

    # ### end Alembic commands ###
