"""1:N relationship

Revision ID: 4ac32c649de1
Revises: b2a8e07953b1
Create Date: 2024-12-25 12:29:09.073516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac32c649de1'
down_revision = 'b2a8e07953b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('todo', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.p_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('todos')
    # ### end Alembic commands ###
